# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target '微博' do




  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


pod 'AFNetworking'
pod 'SDWebImage'
pod 'YYModel'
pod 'FMDB'
pod 'SVProgressHUD'
pod 'pop'

  # Pods for 微博

  target '微博Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '微博UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
